### PR TITLE
sd-bus: use "queue" message references for managing r/w message queue…

### PR DESCRIPTION
**Pull request by jsynacek**
…s in connection objects

Let's make use of the new concept the previous commit added.

See: #4846
(cherry picked from commit c1757a70eac0382c4837a3833d683919f6a48ed7)
Related: CVE-2020-1712

### CODE REVIEW

**Comment by jsynacek** [comment]
I don't understand the ci fails at all.
```
/build/build/../src/libsystemd/sd-daemon/sd-daemon.c:412: undefined reference to `mq_getattr'
```

**Comment by mrc0mmand** [comment]
@jsynacek 

```
FAILED: libnss_myhostname.so.2 
cc  -o libnss_myhostname.so.2 'nss_myhostname@sha/src_nss-myhostname_nss-myhostname.c.o' -Wl,--as-needed -Wl,--no-undefined -shared -fPIC -Wl,--start-group -Wl,-soname,libnss_myhostname.so.2 -Wl,-z,relro -Wl,-z,now -pie -g -O0 -ftrapv src/libsystemd/libsystemd_static.a src/basic/libbasic.a -Wl,-z,nodelete -shared -Wl,--version-script=/build/src/nss-myhostname/nss-myhostname.sym -Wl,--undefined -pthread -lrt /usr/lib64/libcap.so /usr/lib64/libblkid.so /usr/lib64/libmount.so /usr/lib64/libselinux.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/src/libsystemd:$ORIGIN/src/basic' -Wl,-rpath-link,/build/build/src/libsystemd -Wl,-rpath-link,/build/build/src/basic
src/libsystemd/libsystemd_static.a(sd-daemon_sd-daemon.c.o): In function `sd_is_mq':
/build/build/../src/libsystemd/sd-daemon/sd-daemon.c:412: undefined reference to `mq_getattr'
collect2: error: ld returned 1 exit status
```

**Review by dtardon — APPROVED** [review]
LGTM

**Comment by mrc0mmand** [comment]
CI fails:
 * the Travis fail was fixed by https://github.com/systemd-rhel/rhel-8/pull/61/commits/252149c3a477947ee9d994b9cefea29583bd847f - already backported in other branches by https://github.com/lnykryn/systemd-rhel/pull/328
 * LGTM fails on both merge & base branches, it's fixed in RHEL-8.1.0 and later by https://github.com/lnykryn/systemd-rhel/pull/301/files (and following PRs)
 * CentOS CI
     * `TEST-02-CRYPTSETUP` is fixed by https://github.com/systemd-rhel/rhel-8/pull/34/commits in later branches
     * the rest of failing nspawn tests is fixed by https://github.com/lnykryn/systemd-rhel/pull/315 (again, in later branches)

tl;dr none of the current fails are related to the backported patch

**Review by mrc0mmand — APPROVED** [review]
LGTM from the CI point of view

**Comment by mrc0mmand** [comment]
Update: the current LGTM issue is caused by https://discuss.lgtm.com/t/meson-fails-to-determine-sizes-of-basic-datatypes/2639 so it's definitely not caused by the current patchset.
